docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
    - "Tasks and the TaskWorker": tasks.md
    - "Deferred Listeners": deferred-listeners.md
    - "_queued-listeners": queued-listeners.md
site_name: 'phly/phly-swoole-taskworker'
site_description: 'TaskWorker implementation for Swoole tasks'
repo_url: 'https://github.com/phly/phly-swoole-taskworker'
copyright: 'Copyright (c) <a href="https://mwop.net">Matthew Weier O\'Phinney</a>'
